# Site settings
title: Beaker Browser
email: pfrazee@gmail.com
description:
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://beakerbrowser.com" # the base hostname & protocol for your site
twitter_username: pfrazee
github_username:  pfrazee

# Build settings
markdown: kramdown
theme: minima
exclude: ["node_modules"]
gems:
 - jekyll-redirect-from

# Sass
sass:
  style: :compressed
  sass_dir: css

# Site data
collections:
  docs:
    output: true
defaults:
  -
    scope:
      path: ""
      type: "docs"
    values:
      layout: "doc"
